/* CA Solutions OM — Task #12 Firebase Auth + Database bridge.
 * Existing encrypted local storage remains the offline source of truth.
 * Cloud records are encrypted envelopes under the authenticated user's UID.
 */
(() => {
  'use strict';
  const PROJECT_ID='ca-solutions-e397a', AUTH_DOMAIN=PROJECT_ID+'.firebaseapp.com';
  const DB_URL='https://'+PROJECT_ID+'-default-rtdb.asia-southeast1.firebasedatabase.app';
  const MARK='ca_solutions_om_task12_v1';
  const CATEGORY_BY_KEY={workers:'workers',attendance:'attendance',finance:'finance',expenses:'expenses',payments:'payments',transactions:'payments',purchases:'purchases',materials:'materials',stock:'materials',reports:'reports',bills:'reports',sites:'sites'};
  let auth=null,db=null,currentUser=null,syncing=false,initialized=false;
  const cfg=()=>window.CA_FIREBASE_CONFIG||{apiKey:'',authDomain:AUTH_DOMAIN,databaseURL:DB_URL,projectId:PROJECT_ID,storageBucket:PROJECT_ID+'.firebasestorage.app',messagingSenderId:'866641199604',appId:'1:866641199604:web:cb57598d5ddfd32d8d79a1'};
  const json=(v,f=null)=>{try{return JSON.parse(v)}catch{return f}};
  const cat=k=>{k=String(k||'').toLowerCase();for(const [n,c] of Object.entries(CATEGORY_BY_KEY))if(k.includes(n))return c;return'appData'};
  const status=t=>{const e=document.getElementById('caTask12Status');if(e)e.textContent=t||''};
  async function modules(){return await Promise.all([import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js')]);}
  async function database(){return await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js');}
  function styles(){if(document.getElementById('caTask12Styles'))return;const s=document.createElement('style');s.id='caTask12Styles';s.textContent=`#caTask12Gate{position:fixed;inset:0;z-index:120000;background:rgba(15,23,42,.985);display:flex;align-items:center;justify-content:center;padding:16px}#caTask12Gate[hidden]{display:none!important}.ca12-card{width:100%;max-width:420px;background:#1e293b;border:1px solid #475569;border-radius:16px;padding:20px;box-shadow:0 20px 60px rgba(0,0,0,.45)}.ca12-title{font-size:20px;font-weight:800;color:#f59e0b}.ca12-sub{font-size:11px;color:#94a3b8;margin:5px 0 16px}.ca12-field{margin-bottom:10px}.ca12-field label{display:block;font-size:11px;color:#94a3b8;margin-bottom:4px}.ca12-field input{width:100%;padding:10px;background:#0f172a;border:1px solid #334155;border-radius:8px;color:#fff}.ca12-row{display:flex;gap:8px;margin-top:10px}.ca12-row button{flex:1;padding:10px;border:0;border-radius:8px;font-weight:700;cursor:pointer}.ca12-primary{background:#2563eb;color:#fff}.ca12-secondary{background:#334155;color:#fff}.ca12-link{border:0;background:none;color:#60a5fa;text-decoration:underline;cursor:pointer;font-size:11px;padding:4px}.ca12-account{font-size:10px;color:#94a3b8;margin-top:8px;text-align:center}#caTask12Status{min-height:18px;font-size:11px;color:#f59e0b;margin:8px 0;text-align:center}#caTask12Bar{position:fixed;right:10px;top:10px;z-index:110000;display:none;gap:6px;align-items:center;background:#1e293b;border:1px solid #334155;border-radius:10px;padding:6px 8px;font-size:10px;color:#94a3b8}.ca12-online{color:#10b981}.ca12-offline{color:#f59e0b}.ca12-logout{border:0;background:#dc2626;color:#fff;border-radius:6px;padding:5px 8px;font-size:10px;font-weight:700}`;document.head.appendChild(s)}
  function ui(){styles();if(!document.getElementById('caTask12Gate')){const g=document.createElement('div');g.id='caTask12Gate';g.innerHTML=`<div class="ca12-card"><div class="ca12-title">C &amp; A SOLUTIONS</div><div class="ca12-sub">Secure account login. Existing offline data is preserved on this device.</div><div class="ca12-field"><label>Email</label><input id="ca12Email" type="email" autocomplete="email"></div><div class="ca12-field"><label>Password</label><input id="ca12Password" type="password" autocomplete="current-password"></div><div id="caTask12Status"></div><div class="ca12-row"><button id="ca12Login" class="ca12-primary">Login</button><button id="ca12Signup" class="ca12-secondary">Create Account</button></div><div class="ca12-row"><button id="ca12Reset" class="ca12-link">Forgot password?</button></div><div class="ca12-account">Firebase account + per-user cloud isolation</div></div>`;document.body.appendChild(g);g.querySelector('#ca12Login').onclick=()=>login(false);g.querySelector('#ca12Signup').onclick=()=>login(true);g.querySelector('#ca12Reset').onclick=reset}
    if(!document.getElementById('caTask12Bar')){const b=document.createElement('div');b.id='caTask12Bar';b.innerHTML='<span id="ca12Net" class="ca12-offline">Offline</span><span id="ca12User"></span><button id="ca12Logout" class="ca12-logout">Logout</button>';document.body.appendChild(b);b.querySelector('#ca12Logout').onclick=logout}}
  function gate(show){const g=document.getElementById('caTask12Gate'),b=document.getElementById('caTask12Bar');if(g)g.hidden=!show;if(b)b.style.display=show?'none':'flex'}
  async function config(){let c=cfg();if(c.apiKey)return c;try{const r=await fetch(AUTH_DOMAIN+'/__/firebase/init.json',{cache:'no-store'});if(r.ok){const x=await r.json();if(x?.apiKey)c={...c,...x}}}catch{}return c}
  async function init(){if(initialized)return true;const [appMod,authMod,dbMod]=await modules();let c=await config();let app=appMod.getApps().find(a=>a.name==='[DEFAULT]');if(!c.apiKey){status('Firebase Web API configuration is not available. Local data is untouched.');gate(true);return false}
    if(!app||!app.options?.apiKey){try{app=appMod.getApps().find(a=>a.name==='CA_TASK12')||appMod.initializeApp(c,'CA_TASK12')}catch(e){console.error(e);status('Firebase initialization failed; local data remains safe.');gate(true);return false}}
    auth=authMod.getAuth(app);db=dbMod.getDatabase(app,c.databaseURL||DB_URL);await authMod.setPersistence(auth,authMod.browserLocalPersistence);authMod.onAuthStateChanged(auth,async u=>{currentUser=u||null;if(!u){gate(true);return}document.getElementById('ca12User').textContent=u.email||u.uid;gate(false);await sync(u)});initialized=true;window.CATask12={auth,db,user:()=>currentUser,login,logout,resetPassword:reset,sync:()=>currentUser?sync(currentUser):false};return true}
  async function login(create){if(!auth)return;const e=document.getElementById('ca12Email')?.value.trim(),p=document.getElementById('ca12Password')?.value||'';if(!e||!p){status('Email and password are required.');return}status(create?'Creating account…':'Signing in…');try{const m=(await modules())[1];if(create)await m.createUserWithEmailAndPassword(auth,e,p);else await m.signInWithEmailAndPassword(auth,e,p)}catch(x){status(x?.message||'Authentication failed.')}}
  async function reset(){const e=document.getElementById('ca12Email')?.value.trim();if(!e){status('Enter your email first.');return}try{const m=(await modules())[1];await m.sendPasswordResetEmail(auth,e);status('Password reset email sent.')}catch(x){status(x?.message||'Password reset failed.')}}
  async function logout(){if(!auth)return;try{const m=(await modules())[1];await m.signOut(auth)}catch(x){console.error(x)}}
  const keys=()=>Object.values(window.STORAGE_KEYS||{}).filter(Boolean);
  const path=(uid,c,k)=>`users/${uid}/${c}/${encodeURIComponent(k)}`;
  async function write(uid,key,raw){const {ref,set}=await database();const payload={encryptedData:json(raw,raw),updatedAt:Date.now(),key,category:cat(key),schemaVersion:1};await set(ref(db,path(uid,'appData',key)),payload);await set(ref(db,path(uid,cat(key),key)),payload)}
  async function sync(u){if(!u||!db||syncing)return;syncing=true;try{const {ref,get,set}=await database();const snap=await get(ref(db,`users/${u.uid}`)),cloud=snap.exists()?(snap.val()||{}):{};for(const key of keys()){const raw=localStorage.getItem(key),node=cloud.appData?.[encodeURIComponent(key)]||cloud.appData?.[key];if(!raw&&node){const env=node.encryptedData??node;localStorage.setItem(key,JSON.stringify(env));try{window.CAApplyRemoteEncryptedRecord?.(key,env,Number(node.updatedAt)||0)}catch{}}else if(raw){await set(ref(db,path(u.uid,'appData',key)),{encryptedData:json(raw,raw),updatedAt:Date.now(),key,category:cat(key),schemaVersion:1})}}localStorage.setItem(MARK,JSON.stringify({uid:u.uid,lastSyncAt:Date.now(),version:1}));status(navigator.onLine?'Cloud sync complete.':'Offline — local changes preserved.');}catch(x){console.warn('Task 12 sync deferred',x);status(navigator.onLine?'Cloud sync deferred; local data preserved.':'Offline — local changes preserved.')}finally{syncing=false}}
  function patchSave(){if(window.__caTask12SavePatched)return;const original=window.saveStorage;if(typeof original!=='function')return;window.saveStorage=function(key,value){const r=original.apply(this,arguments);if(currentUser&&db&&navigator.onLine)write(currentUser.uid,key,localStorage.getItem(key)).catch(()=>{});return r};window.__caTask12SavePatched=true}
  function net(){const e=document.getElementById('ca12Net');if(e){e.textContent=navigator.onLine?'Online':'Offline';e.className=navigator.onLine?'ca12-online':'ca12-offline'}}
  async function boot(){ui();net();window.addEventListener('online',()=>{net();if(currentUser)sync(currentUser)});window.addEventListener('offline',net);await init();patchSave();net()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
